#!/usr/bin/env python

# The source/keybindings.json file is:
#
# * pretty-printed for editing;
# * not actually valid JSON, as it's commented using C++ style // comments.
# 
# This script strips the comments and prints it compactly,
# as build/keybindings.json.
#
# TODO: Don't strip lines with "//" in a string!

import sys
import codecs
import json

def decomment(l):
    if len(l) < 2:
        return l
    elif l[0:2] == "//":
        return ""
    return l[0] + decomment(l[1:])

decommented = "\n".join(map(decomment, codecs.open(sys.argv[1], "r", "utf-8").read().splitlines()))

json.dump(json.loads(decommented), codecs.open(sys.argv[2], "w", "utf-8"), ensure_ascii = False)
